server:
  port: 8762
debug: true
spring:
  # HTTP ENCODING
  http:
     encoding.charset: UTF-8
     encoding.force: true
     encoding:
      enabled: true
  application:
     name: @project.name@
security:
  basic:
    enabled: false #开启认证
  user:
    name: user
    password: 123456
eureka:
  instance:
    hostname: localhost
    metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
