server:
  port: 8761

#    默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod

spring:
  profiles:
    active: dev

debug: true

---
#测试环境
spring:
  profiles: dev
  # HTTP ENCODING
  http:
     encoding.charset: UTF-8
     encoding.force: true
     encoding:
      enabled: true
  application:
     name: eureka-service
security:
  basic:
    enabled: false #开启认证
  user:
    name: user
    password: 123456
eureka:
  instance:
    hostname: localhost
    metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/
